// Generated by gencpp from file serial_com/uwb.msg
// DO NOT EDIT!


#ifndef SERIAL_COM_MESSAGE_UWB_H
#define SERIAL_COM_MESSAGE_UWB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_com
{
template <class ContainerAllocator>
struct uwb_
{
  typedef uwb_<ContainerAllocator> Type;

  uwb_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , angle(0.0)  {
    }
  uwb_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::serial_com::uwb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_com::uwb_<ContainerAllocator> const> ConstPtr;

}; // struct uwb_

typedef ::serial_com::uwb_<std::allocator<void> > uwb;

typedef boost::shared_ptr< ::serial_com::uwb > uwbPtr;
typedef boost::shared_ptr< ::serial_com::uwb const> uwbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_com::uwb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_com::uwb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_com::uwb_<ContainerAllocator1> & lhs, const ::serial_com::uwb_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_com::uwb_<ContainerAllocator1> & lhs, const ::serial_com::uwb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_com

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::serial_com::uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_com::uwb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_com::uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_com::uwb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_com::uwb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_com::uwb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_com::uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b5ea1805e9322c86a7b0bff9ff9764e";
  }

  static const char* value(const ::serial_com::uwb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b5ea1805e9322c8ULL;
  static const uint64_t static_value2 = 0x6a7b0bff9ff9764eULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_com::uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_com/uwb";
  }

  static const char* value(const ::serial_com::uwb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_com::uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 angle\n"
;
  }

  static const char* value(const ::serial_com::uwb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_com::uwb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct uwb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_com::uwb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_com::uwb_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_COM_MESSAGE_UWB_H
